# Generated by Django 6.0 on 2025-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('editor', 'Editor'), ('writer', 'Writer')], max_length=20, null=True),
        ),
    ]
