# Generated by Django 6.0 on 2026-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('reader', 'Lector'), ('editor', 'Editor'), ('writer', 'Escritor')], max_length=20, null=True),
        ),
    ]
